name: hierarchical-walks
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pandas
  - networkx
  - tqdm
  - scikit-learn
  - pip
  - pip:
    - absl-py==2.0.0
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - annotated-types==0.6.0
    - antlr4-python3-runtime==4.9.3
    - async-timeout==4.0.3
    - attrs==23.1.0
    - cachetools==5.3.2
    - charset-normalizer==3.3.2
    - filelock==3.13.1
    - fonttools==4.25.0
    - frozenlist==1.4.0
    - fsspec==2023.10.0
    - google-auth==2.23.4
    - google-auth-oauthlib==1.1.0
    - grpcio==1.59.2
    - hydra-core==1.3.2
    - idna==3.4
    - Jinja2==3.1.2
    - lightning==2.1.0
    - lightning-utilities==0.9.0
    - Markdown==3.5.1
    - markdown-it-py==3.0.0
    - MarkupSafe==2.1.3
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.0.4
    - munkres==1.1.4
    - nltk==3.8.1
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - protobuf==4.23.4
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pydantic==2.4.2
    - pydantic_core==2.10.1
    - Pygments==2.16.1
    - pytorch-lightning==2.1.0
    - PyYAML==6.0.1
    - regex==2023.10.3
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rich==13.6.0
    - rsa==4.9
    - sympy==1.12
    - seaborn==0.13.0
    - tensorboard==2.15.1
    - tensorboard-data-server==0.7.2
    - torch==2.1.0
    - torchdata==0.7.0
    - torchmetrics==1.2.0
    - torchtext==0.16.0
    - typing_extensions==4.8.0
    - urllib3==2.0.7
    - Werkzeug==3.0.1
    - yarl==1.9.2


