defaults:
  - base
  - datamodule: cora

train:
  experiment: 'cora_adv_n2v_hw_random_edge_addition'

datamodule:
  additional_parameters:
    method: adv_node2vec
    method_params:
      prior_transformation: randomly_add_edges
      num_perturbations_prior: 525
      step_transformation: do_nothing
      num_perturbations_step: 0
      p: 1
      q: 2.0
    
    walks_per_node: 8
    walk_length: 8
    
    num_compressions: 2
    compression_selection_ratio: .5

