defaults:
  - base
  - datamodule: cora

train:
  experiment: 'cora_n2v_hw'

datamodule:
  additional_parameters:
    method: node2vec
    method_params:
      p: 1
      q: 2.0
    
    walks_per_node: 8
    walk_length: 8
    
    num_compressions: 2
    compression_selection_ratio: .5
