defaults:
  - base
  - datamodule: cora

train:
  experiment: 'cora_dw_hw'

datamodule:
  additional_parameters:
    method: deepwalk
    
    walks_per_node: 8
    walk_length: 8
    
    num_compressions: 2
    compression_selection_ratio: .5
