defaults:
  - base
  - datamodule: ppi

train:
  experiment: 'ppi_adv_dw_degree_node_removal'

datamodule:  
  additional_parameters:
    method: adv_deepwalk
    method_params:
      prior_transformation: remove_nodes_degree_centrality
      num_perturbations_prior: 2850
      step_transformation: do_nothing
      num_perturbations_step: 0

    walks_per_node: 8
    walk_length: 8
    
    num_compressions: 0
    compression_selection_ratio: 0